### ISSUE TITLE
Deixar tudo em caixa alta (maiúsculo)

### ISSUE THREAD

**Issue by kelsoncm** [CoticEaDIFRN/baggins#1]
Solicitado por @fabiano_faustino

**Comment by kelsoncm** [comment]
Desrespeitando: 

1.  A regra culta? 
2. Quem Escreve Assim? 
3. OU ASSIM?

**Comment by ffo13** [comment]
kkkkk, é toc meu, kkkk
Como vejo muito dessas coisas no suap, fico com essas besteiras besta.
No suap, temos cadastros de todos os tipos, até nomes pessoais em minúsculo.
Deixa do jeito que está mesmo.

**Comment by kelsoncm** [comment]
Certo, vou fechar!
