### ISSUE TITLE
Se chamado, destacar o candidato

### ISSUE THREAD

**Issue by kelsoncm** [CoticEaDIFRN/baggins#10]
a pedido de @ffo13 .

**Comment by kelsoncm** [comment]
Destacar onde? Na listagem?

**Comment by ffo13** [comment]
Destacar na listagem. Seria apenas para saber se aquele candidato foi chamado ou não. Se foi chamado, o fundo poderia ficar verde. Serviria apenas para orientação ao visualizar o cadastro de reserva.

**Comment by kelsoncm** [comment]
OK. @ffo13 , o que você acha de ser baseado no campo "Convocado em"? Assim não seria necessário informar dois campos. Ainda tem os campos "Assumiu em" e "Desistência em" que podem ser usados para outras coisas.

**Comment by ffo13** [comment]
Ótimo!

**Comment by kelsoncm** [comment]
Nota pessoal:

Estudar esta possibilidade http://djangosuit.com/admin/examples/continent/ ou esta https://github.com/litchfield/django-liststyle/blob/master/liststyle/templates/admin/change_list_results.html

**Comment by ffo13** [comment]
Qndo clico no primeiro link, solicita user e senha e no abre o código fonte, é isso mesmo?

**Comment by kelsoncm** [comment]
É, era apenas uma pedaço de uma pesquisa que fiz. era mais uma nota pessoal para mim mesmo, mas se quiser dar uma olhada, até para se inspirar, o usuário e a senha estão na página de login, é demo/demo.

É um plugin que posso usar para alterar diversas coisas no tema.

**Comment by ffo13** [comment]
Vi agora, fica legal esse layout. Era isso mesmo!
