### ISSUE TITLE
Colocar campo para registro das horas ou puxar do suap a carga horária daquele mês (número de horas e relatório)

### ISSUE THREAD

**Issue by kelsoncm** [CoticEaDIFRN/baggins#12]
a pedido de @ffo13

**Comment by kelsoncm** [comment]
É para que mesmo?

**Comment by ffo13** [comment]
A bolsa é paga, analisando os seguintes critérios:
Número de horas computada no mês (h)
Dias úteis no mês (d)
Valor da hora daquela função (v)

Observações: 
Se o mês tiver menos de 20 dias úteis, então ninguém receberá a bolsa cheia. Ela é paga sobre os dias úteis.

**Comment by kelsoncm** [comment]
Então @ffo13 , será apenas um campo informativo, certo? Imagino que fará sentido quando tivermos integrados com o SUAP.

**Comment by ffo13** [comment]
Esse número de dias úteis, é essencial para o cálculo do pagamento

**Comment by kelsoncm** [comment]
Mas o cálculo não é feito por hora?

**Comment by ffo13** [comment]
Sim, é por hora! Mas deve respeitar a condição de número de dias para não ultrapassar a hora do mês. 
Por exemplo: 
No mês de novembro, devido aos feriados, tivemos 19 dias úteis, o que obrigaria uma carga horária de 38h e 76h no mês para os cargos de 10h/semana e 20h/semana. Neste caso, muita gente trabalhou o mês fechando as 40 e 80h para receberem cheio, mas como o mês só tinha 19 dias, ninguém recebeu cheio, por mais que tenha feito as horas a mais. 
Então, o número de dias dispara para saber qntas horas aquele bolsista tera que pagar.

**Comment by kelsoncm** [comment]
Então parece mais ser apropriado gerar um sistema de calendário, assim poderíamos informar todo início de mês quantos dias (e também quantas horas?) serão necessários para aquela competência.

Ex:. 2017/12 - 19d; 2018/01 - 20d. 

Que tal?

**Comment by ffo13** [comment]
Acho uma boa!
Tem que ter a questão das horas tb
