### ISSUE TITLE
VAGAS - No campo “Carga horária”, acredito que seja “Número de Vagas”

### ISSUE THREAD

**Issue by kelsoncm** [CoticEaDIFRN/baggins#4]
a pedido de @fabiano_faustino

**Comment by kelsoncm** [comment]
1. Não, é carga horária mesmo.
2. Como não é um sistema de seleção, o real interesse é em saber para quantas horas a pessoa vinculada a esta vaga foi contratada.
3. Pode até ter este campo extra que indique o número de vagas previsto no edital, mas como podem ser chamados além do previsto (cadastro reserva) acho que não compensa.

**Comment by ffo13** [comment]
A carga horária é semanal! Acabei colocando mensal de forma equivocada.

**Comment by kelsoncm** [comment]
Se é sempre semanal, precisa de um Tipo de Carga Horária?

**Comment by ffo13** [comment]
Seria bom ter em algum local informando essa carga horária.

**Comment by kelsoncm** [comment]
A carga horária vai ter, pergunto pela tipo de carga horária, ou seja, Semanal e/ou Mensal.

**Comment by ffo13** [comment]
No edital diz que é semanal. 
Por mim, seria mensal que daria na mesma. 
Semanal multiplicaria por 4 e mensal dividiria se fosse o caso. 
Se tiver como ser “Semanal e/ou Mensal”, o responsável optaria.

**Comment by kelsoncm** [comment]
Feito
