### ISSUE TITLE
Termo de desistência tem que ter a opção de anexar documentos.

### ISSUE THREAD

**Issue by kelsoncm** [CoticEaDIFRN/baggins#7]
a pedido de @ffo13

**Comment by kelsoncm** [comment]
Boa. Melhor que apenas a identificação do termo para procurar na pasta é ter o documento digitalizado.

**Comment by ffo13** [comment]
Show de bola.

**Comment by kelsoncm** [comment]
Será assim então!

**Comment by kelsoncm** [comment]
Será resolvido no #13
