### ISSUE TITLE
Opção para cadastrar apenas o cadastros de reserva, com menos informações (Endereço, dados bancários…)

### ISSUE THREAD

**Issue by kelsoncm** [CoticEaDIFRN/baggins#8]
a pedido de @ffo13 .

**Comment by kelsoncm** [comment]
Você quer ter menos campos obrigatórios no cadastro de pessoa física ou ter um cadastro de reserva que não seja uma pessoa física. Pois é uma ou outra. Entende o motivo né? Todos os campos para cadastro de pessoa física são padrões, uma cadastro reserva é uma pessoa física reserva em uma vaga, portanto, PF e Vaga tem que ser preenchidos antes. Ou ter o cadastro de reserva diferente do cadastro de pessoa física. Ver anexo.

**Comment by ffo13** [comment]
Vamos esquecer isso!!! 
A questão que visualizei foi que, quando estava fazendo o cadastro de reserva, percebi que não tinha todos os dados dos candidatos em mãos, mas analisando corretamente, no ato de inscrição, todos os candidatos enviam a documentação exigida.

**Comment by kelsoncm** [comment]
OK @ffo13 , vou fechar então.
